# Generated by Django 6.0.5 on 2026-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('dado_golpe', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'clase',
                'verbose_name_plural': 'clases',
                'db_table': 'srd_clases',
            },
        ),
        migrations.CreateModel(
            name='Conjuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('escuela', models.CharField(max_length=50)),
                ('concentracion', models.BooleanField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'conjuro',
                'verbose_name_plural': 'conjuros',
                'db_table': 'srd_conjuros',
            },
        ),
        migrations.CreateModel(
            name='Monstruo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('clase_armadura', models.PositiveSmallIntegerField()),
                ('puntos_golpe', models.PositiveSmallIntegerField()),
                ('fuerza', models.PositiveSmallIntegerField()),
                ('destreza', models.PositiveSmallIntegerField()),
                ('constitucion', models.PositiveSmallIntegerField()),
                ('inteligencia', models.PositiveSmallIntegerField()),
                ('sabiduria', models.PositiveSmallIntegerField()),
                ('carisma', models.PositiveSmallIntegerField()),
                ('desafio', models.CharField(max_length=10)),
                ('acciones', models.JSONField()),
                ('acciones_legendarias', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'monstruo',
                'verbose_name_plural': 'monstruos',
                'db_table': 'srd_monstruos',
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('rareza', models.CharField(max_length=50)),
                ('es_magico', models.BooleanField()),
            ],
            options={
                'verbose_name': 'objeto',
                'verbose_name_plural': 'objetos',
                'db_table': 'srd_objetos',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('incremento_atributos', models.JSONField()),
                ('velocidad', models.PositiveIntegerField()),
                ('idiomas', models.JSONField()),
                ('rasgos_raciales', models.JSONField()),
            ],
            options={
                'verbose_name': 'raza',
                'verbose_name_plural': 'razas',
                'db_table': 'srd_razas',
            },
        ),
    ]
