# Generated by Django 6.0.5 on 2026-05-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='rareza',
            field=models.CharField(max_length=100),
        ),
    ]
