# Generated by Django 6.0.5 on 2026-05-23 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homebrew', '0001_initial'),
        ('srd', '0002_alter_objeto_rareza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('notas_generales', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas_dirigidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'campaña',
                'verbose_name_plural': 'campañas',
                'db_table': 'user_campanas',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('experiencia', models.PositiveIntegerField(default=0)),
                ('fuerza', models.PositiveSmallIntegerField()),
                ('destreza', models.PositiveSmallIntegerField()),
                ('constitucion', models.PositiveSmallIntegerField()),
                ('inteligencia', models.PositiveSmallIntegerField()),
                ('sabiduria', models.PositiveSmallIntegerField()),
                ('carisma', models.PositiveSmallIntegerField()),
                ('puntos_golpe_max', models.PositiveSmallIntegerField()),
                ('puntos_golpe_actuales', models.SmallIntegerField()),
                ('clase_armadura', models.PositiveSmallIntegerField()),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes', to='campaigns.campana')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personajes', to='srd.raza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'personaje',
                'verbose_name_plural': 'personajes',
                'db_table': 'user_personajes',
            },
        ),
        migrations.CreateModel(
            name='PersonajeClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_en_clase', models.PositiveSmallIntegerField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='srd.clase')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.personaje')),
            ],
            options={
                'verbose_name': 'clase de personaje',
                'verbose_name_plural': 'clases de personaje',
                'db_table': 'personaje_clases',
            },
        ),
        migrations.AddField(
            model_name='personaje',
            name='clases',
            field=models.ManyToManyField(related_name='personajes', through='campaigns.PersonajeClase', to='srd.clase'),
        ),
        migrations.CreateModel(
            name='PersonajeConjuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparado', models.BooleanField(default=False)),
                ('conjuro_hb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='homebrew.hechizo')),
                ('conjuro_srd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='srd.conjuro')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuros_conocidos', to='campaigns.personaje')),
            ],
            options={
                'verbose_name': 'conjuro de personaje',
                'verbose_name_plural': 'conjuros de personaje',
                'db_table': 'personaje_conjuros',
            },
        ),
        migrations.CreateModel(
            name='PersonajeInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('equipado', models.BooleanField(default=False)),
                ('objeto_hb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='homebrew.objeto')),
                ('objeto_srd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='srd.objeto')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='campaigns.personaje')),
            ],
            options={
                'verbose_name': 'item de inventario',
                'verbose_name_plural': 'inventario',
                'db_table': 'personaje_inventario',
            },
        ),
        migrations.AddConstraint(
            model_name='personajeclase',
            constraint=models.UniqueConstraint(fields=('personaje', 'clase'), name='unique_personaje_clase'),
        ),
        migrations.AddConstraint(
            model_name='personajeconjuro',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conjuro_hb__isnull', True), ('conjuro_srd__isnull', False)), models.Q(('conjuro_hb__isnull', False), ('conjuro_srd__isnull', True)), _connector='OR'), name='conjuro_exactamente_uno', violation_error_message='Un conjuro conocido debe referenciar exactamente un hechizo (SRD u Homebrew), nunca ambos ni ninguno.'),
        ),
        migrations.AddConstraint(
            model_name='personajeinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('objeto_hb__isnull', True), ('objeto_srd__isnull', False)), models.Q(('objeto_hb__isnull', False), ('objeto_srd__isnull', True)), _connector='OR'), name='inventario_exactamente_un_objeto', violation_error_message='Un ítem de inventario debe referenciar exactamente un objeto (SRD u Homebrew), nunca ambos ni ninguno.'),
        ),
    ]
