# Generated by Django 6.0.5 on 2026-05-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='alineamiento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personaje',
            name='trasfondo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
