# Generated by Django 6.0.5 on 2026-05-23 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hechizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('escuela', models.CharField(max_length=50)),
                ('concentracion', models.BooleanField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hechizo homebrew',
                'verbose_name_plural': 'hechizos homebrew',
                'db_table': 'homebrew_hechizos',
                'constraints': [models.UniqueConstraint(fields=('nombre', 'creador'), name='unique_hechizo_por_creador')],
            },
        ),
        migrations.CreateModel(
            name='Monstruo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clase_armadura', models.PositiveSmallIntegerField()),
                ('acciones', models.JSONField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'monstruo homebrew',
                'verbose_name_plural': 'monstruos homebrew',
                'db_table': 'homebrew_monstruos',
                'constraints': [models.UniqueConstraint(fields=('nombre', 'creador'), name='unique_monstruo_por_creador')],
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('es_magico', models.BooleanField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'objeto homebrew',
                'verbose_name_plural': 'objetos homebrew',
                'db_table': 'homebrew_objetos',
                'constraints': [models.UniqueConstraint(fields=('nombre', 'creador'), name='unique_objeto_por_creador')],
            },
        ),
    ]
